import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import AuthProvider from "./services/AuthProvider";


const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700", "900"],
});

export const metadata = {
  title: "Slice Haven",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
          <AuthProvider>
               <main className="max-w-4xl mx-auto p-4">
            <Navbar />
            {children}
          </main>
          <Footer />
          </AuthProvider>
       

      </body>
    </html>
  );
}
